        # === ???? ===
server.port=8080

# === ? ?????? (??????) ===
# ?????????? /
file.upload.dir=D:/fyp_uploads/

# === ? ??????? ===
# ?????????? MySQL ??? 123456??????????
spring.datasource.url=jdbc:mysql://localhost:3306/twieeetter_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123wangyuboA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

meilisearch.enabled=true
meilisearch.host=http://127.0.0.1:7700
meilisearch.api-key=abc123456
meilisearch.index=tweets

spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=906427984@qq.com
spring.mail.password=cvrhpufftiwfbfid
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

app.mail.from=906427984@qq.com
app.base-url=http://localhost:8080
app.digest.cron=0 0 8 * * ?
